[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="*"
rayon="1.6.1"

[dependencies.indicatif]
version="0.17.3"
features=["rayon"]